main: dev.dejay.evenbetterrtp..Main
version: ${project.version}
name: BetterRTP
author: [SuperRonanCraft, DeJayDev]
softdepend: [Vault, WorldGuard, GriefPrevention, Factions]
api-version: 1.16

commands:
    betterrtp:
        aliases: [brtp, rtp]
        description: Randomly teleport to a location

permissions:
    betterrtp.*:
        children:
            betterrtp.use: true
            betterrtp.world.*: true
            betterrtp.bypass.*: true
            betterrtp.player: true
            betterrtp.reload: true
            betterrtp.biome: true
    betterrtp.world.*:
        description: RTP in all enabled worlds
    betterrtp.bypass.*:
            children:
                betterrtp.bypass.cooldown: true
                betterrtp.bypass.delay: true
                betterrtp.bypass.economy: true
    betterrtp.use:
        description: Use RTP command
        default: true
    betterrtp.world:
        description: Use world command
    betterrtp.player:
        description: RTP another player
    betterrtp.biome:
        description: RTP to specific biomes
    betterrtp.sign:
        description: Ability to create an RTP sign
    betterrtp.bypass.cooldown:
        description: Bypass cooldowns
    betterrtp.bypass.delay:
        description: Bypass delays
    betterrtp.bypass.economy:
        description: Bypass economy
    betterrtp.reload:
        description: Reload the config
        default: op
    betterrtp.info:
        description: View info about all worlds rtp will work in
        default: op