main: dev.dejay.evenbetterrtp.Main
version: ${project.version}
name: EvenBetterRTP
author: [SuperRonanCraft, DeJayDev]
softdepend: [Vault, WorldGuard, GriefPrevention, Factions]
api-version: 1.16

commands:
    evenbetterrtp:
        aliases: [ebrtp, brtp, rtp]
        description: Randomly teleport to a location

permissions:
    evenbetterrtp.*:
        children:
            evenbetterrtp.use: true
            evenbetterrtp.world.*: true
            evenbetterrtp.bypass.*: true
            evenbetterrtp.player: true
            evenbetterrtp.reload: true
            evenbetterrtp.biome: true
    evenbetterrtp.world.*:
        description: RTP in all enabled worlds
    evenbetterrtp.bypass.*:
            children:
                evenbetterrtp.bypass.cooldown: true
                evenbetterrtp.bypass.delay: true
                evenbetterrtp.bypass.economy: true
    evenbetterrtp.use:
        description: Use RTP command
        default: true
    evenbetterrtp.world:
        description: Use world command
    evenbetterrtp.player:
        description: RTP another player
    evenbetterrtp.biome:
        description: RTP to specific biomes
    evenbetterrtp.sign:
        description: Ability to create an RTP sign
    evenbetterrtp.bypass.cooldown:
        description: Bypass cooldowns
    evenbetterrtp.bypass.delay:
        description: Bypass delays
    evenbetterrtp.bypass.economy:
        description: Bypass economy
    evenbetterrtp.reload:
        description: Reload the config
        default: op
    evenbetterrtp.info:
        description: View info about all worlds rtp will work in
        default: op